In [1]:
import numpy as np
print("setup compelete")

setup compelete


In [2]:
ar=np.array([1,2,3,4])

In [3]:
ar

array([1, 2, 3, 4])

In [5]:
ar.dtype

dtype('int32')

In [6]:
# Dimension
ar.ndim

1

In [7]:
# Taille
ar.size

4

In [9]:
# Forme
ar.shape

(4,)

In [10]:
# Indexation comme dans les listes
ar[0]

1

In [11]:
ar[1]

2

In [12]:
ar[-1]

4

In [13]:
# Cas d'un tableau multi dimentionnel

In [14]:
ar1 = np.array([[1,2,3],[4,5,6]])

In [16]:
ar1[0,0]

1

In [17]:
ar1[1,0]

4

In [18]:
ar1[1,0] = 5

In [19]:
ar1[1,0]

5

In [21]:
ar1

array([[1, 2, 3],
       [5, 5, 6]])

In [22]:
ar1[1,2]=np.pi

In [23]:
ar1

array([[1, 2, 3],
       [5, 5, 3]])

In [24]:
ar2 = np.arange(0,20,3)

In [25]:
ar2

array([ 0,  3,  6,  9, 12, 15, 18])

In [26]:
ar3 = ar2[:5]
ar3

array([ 0,  3,  6,  9, 12])

In [27]:
ar3[:4:2]

array([0, 6])

In [28]:
ar3[3::-1]

array([9, 6, 3, 0])

In [29]:
ar1.shape

(2, 3)

In [30]:
ar4 = ar1.reshape(3,2)

In [31]:
ar4

array([[1, 2],
       [3, 5],
       [5, 3]])