In [1]:
import numpy as np
print("setup complete")

setup complete


In [11]:
ar = np.array([1,2,3,4])
ar

array([1, 2, 3, 4])

In [3]:
ar1 = np.concatenate([ar, ar])
ar1

array([1, 2, 3, 4, 1, 2, 3, 4])

In [4]:
ar2 = np.array([[1,2,3],[4,5,6]])

In [5]:
ar2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
ar3 = np.concatenate([ar2, ar2])
ar3
# par defaut, axe 0, vertical

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [9]:
ar4 = np.concatenate([ar2, ar2], axis=1)
ar4

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [10]:
ar[1:]

array([2, 3, 4])

In [12]:
np.vstack([ar[1:], ar2])

array([[2, 3, 4],
       [1, 2, 3],
       [4, 5, 6]])

In [140]:
ar5 = np.hstack([ar4, np.array([[1],[2]])])

In [20]:
np.hstack([ar4, ar4])

array([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6]])

In [86]:
ar6 = np.arange(0,20,2)
ar6

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [90]:
a1, a2 = np.split(ar6, [5])
print(a1,a2)

[0 2 4 6 8] [10 12 14 16 18]


In [98]:
a1, a2,a3 = np.split(ar6, [1,5])
print(a1,a2,a3)

[0] [2 4 6 8] [10 12 14 16 18]


In [72]:
a1

array([0, 3])

In [73]:
a2

array([ 6,  9, 12, 15, 18])

In [65]:
a3

array([ 3,  6,  9, 12, 15, 18])

In [136]:
a1, a2,a3,a4,a5,a6 = np.split(ar6, [1,3,4,5,6])
print(a1,a2,a3,a4,a5)

[0] [2 4] [6] [8] [10]


In [137]:
ar6_1, ar6_2 = np.vsplit(ar4, [1])
ar6_1

array([[1, 2, 3, 1, 2, 3]])

In [138]:
ar6_2

array([[4, 5, 6, 4, 5, 6]])

In [141]:
ar5

array([[1, 2, 3, 1, 2, 3, 1],
       [4, 5, 6, 4, 5, 6, 2]])

In [142]:
ar5.transpose()

array([[1, 4],
       [2, 5],
       [3, 6],
       [1, 4],
       [2, 5],
       [3, 6],
       [1, 2]])

In [143]:
np.save('exempleTab.numpy',ar6)

In [144]:
ar7 = np.load('exempleTab.numpy.npy')
ar7

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])